.gitignore
Gemfile
Gemfile.lock
Jenkinsfile
Rakefile
lib/tasks/build.rake
lib/tasks/build_artifact.rake
lib/tasks/prerm
lib/tasks/uitpas-balie.service

- Ruby build tools
- Artifact build rake tasks
- Jenkins pipeline definition
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4347

Add artifact build related code

---

Jenkinsfile

---
Ticket: https://jira.uitdatabank.be/browse/...

Correct escape character for comments is // in Jenkinsfile

---

src/feature-counter/components/CounterPicker.tsx

- Automatic selection of a counter when the user only has one counter to choose from
---
Ticket: [#UPS-4345](https://jira.publiq.be/browse/UPS-4345)

feat: automatically select counter

---

src/feature-activities/components/ActivitiesPage.tsx

Reverts cultuurnet/uitpas-balie-frontend#11

Revert "UPS-4652-Fix audienceType on Activities page"

---

package.json
src/lib/ui/uitpas/Pagination.tsx
src/lib/utils/hooks/usePagination.ts
yarn.lock

Refs #UPS-4652
@mui/material toegevoegd: Deze heeft een usePagination hook die berekend waar er ellipsis moeten komen wanneer je veel pagina's hebt.
_Later te bekijken of we bepaalde zaken migreren naar andere componenten van @mui/material. @mui/joy die we nu gebruiken bevat toch wel een stuk minder functionaliteit en componenten._
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4652

fix: add ellipsis to pagination

---

README.md
lib/getPathsFromFolderStructure.js
next.config.js
src/feature-legacy/hooks/useUrlChanged.ts

https://jira.uitdatabank.be/browse/UPS-4891

fix: only use the nextjs router when the path exists in nextjs

---

src/mobile/layouts/navbar/MobileNavBar.tsx

- Mobile navbar is now sticky and always visible when scrolling vertically
---
Ticket: [#UPS-5075](https://jira.publiq.be/browse/UPS-5075)

feat(navbar): make navbar sticky

---

src/mobile/feature-identification/components/IdentificationPage.tsx
src/mobile/feature-identification/components/ManualCardInput.tsx
src/mobile/feature-identification/scan/components/BarcodeScanner.tsx
src/mobile/feature-saving/components/MobileSavingPage.tsx
src/mobile/lib/ui/uitpas/Alert.tsx

- An animation the already existing Alert component to make it more obvious of the change of data or position. 
---
Ticket: [#UPS-5076](https://jira.publiq.be/browse/UPS-5076)

feat: show animation when entering new number

---

src/mobile/feature-saving/components/MobileSavingPage.tsx
src/mobile/feature-saving/components/Tariff.tsx
src/mobile/feature-saving/components/TariffCard.tsx
src/mobile/feature-saving/components/TariffDrawer.tsx
src/shared/lib/i18n/locales/nl/common.json

- Displaying a loading spinner inside of the tariff drawer when fetching data
- Tariff drawer now displays a message when there are no tariffs available
- Prices that are 0 no longer are queried for their tariffs
- Coupons in tariff drawer show the correct coupon sentence
---
Ticket: [#UPS-5027](https://jira.publiq.be/browse/UPS-5027)

fix: tariffs discounts

---

src/mobile/feature-identification/components/ManualCardInput.tsx
src/mobile/feature-saving/components/MobileSavingPage.tsx

- Request to save points was not being made when entering/scanning another card.
---
Ticket: [#UPS-5077](https://jira.publiq.be/browse/UPS-5077)

fix: POST request to savings endpoint not using new uitpasNumber

---

src/mobile/feature-saving/components/Tariff.tsx
src/mobile/feature-saving/components/TariffDrawer.tsx

Refs: #UPS-5079
- Force refetch data (event & tariffs) upon opening tariffs drawer
---
Ticket: [#UPS-5079](https://jira.publiq.be/browse/UPS-5079)

feat: force refetch data on tariffs

---

src/mobile/feature-saving/components/tariff/Tariff.tsx

- Usage of the useQueries hook
- Choosing tariffs stuck in loading
---
Ticket: [#UPS-5101](https://jira.publiq.be/browse/UPS-5101)

fix: tanstack useQueries syntax after upgrade

---

src/mobile/feature-activities/components/ActivitiesPage.tsx
src/shared/lib/utils/dateUtils.ts

Refs: #UPS-5103
- Params dateFrom & dateTo to query of events
---
Ticket: [#UPS-5103](https://jira.publiq.be/browse/UPS-5103)

refactor: add dateFrom & dateTo params to query

---

src/mobile/feature-saving/components/reward/RewardPicker.tsx
src/mobile/feature-saving/components/reward/RewardsDrawer.tsx

- Rewards drawer setting the scroll position each time you open/close it
---
Ticket: [#UPS-5102](https://jira.publiq.be/browse/UPS-5102)

fix: scroll position within rewards drawer

---

package.json
src/app/layout.tsx
src/mobile/feature-counter/components/CounterPage.tsx
src/shared/lib/utils/polyfills.ts
yarn.lock

- Support for toSorted() method via polyfilling
---
Ticket: [#UPS-5152](https://jira.publiq.be/browse/UPS-5152)

fix: add toSorted polyfill

---

package.json
src/mobile/feature-identification/components/IdentificationPage.tsx
src/mobile/feature-identification/scan/components/BarcodeScanner.tsx
src/shared/lib/utils/hooks/useCamera.ts
yarn.lock

- WebRTC adapter package
- Disabling of barcode scanner button when scanner fails to load after 5 attempts
- Scan within specific area (which is visible on screen)
- Borders of the area will turn green when a barcode has been scanned
- Quagga2 config which should result in better scan & image results
---
Ticket: [#UPS-5152](https://jira.publiq.be/browse/UPS-5152)

fix: barcode scanner improvements

---

src/mobile/feature-identification/components/ManualCardInput.tsx

Fix typo in parameter name from 'inz' to 'insz' to correctly pass inszNumber to /passholders API
Ticket: https://jira.publiq.be/browse/UPS-5228

UPS-5228 - fix typo search for insz

---

src/mobile/layouts/navbar/MobileNavBar.tsx
src/mobile/layouts/navbar/components/NavBarIcon.tsx
src/mobile/layouts/navbar/components/NavBarItemContainer.tsx
src/mobile/layouts/navbar/components/NavBarTypography.tsx
src/shared/lib/i18n/locales/nl/common.json

- Logout button when there is no counter selected, which should only be visible on the select counter page.
---
Ticket: [#UPS-4979](https://jira.publiq.be/browse/UPS-4979)

feat: logging out of mobile counter app

---

src/shared/lib/utils/hooks/useCamera.ts

fix: only ask permission if access was not granted before

---

src/shared/lib/utils/hooks/useDetectMobile.ts

- `useDetectMobile` hook to no longer redirect back to web version when already on mobile version. 
---
Ticket: [#UPS-5303](https://jira.publiq.be/browse/UPS-5303)

feat: allow non-mobile devices to use mobile version

---

src/mobile/feature-counter/components/CounterPage.tsx
src/shared/feature-counter/hooks/useGetCounters.ts
src/web/feature-counter/components/SelectCounterPage.tsx

Refs #UPS-4869
- Created shared logic for sorting and filtering counter select page between mobile & web.
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4869

feat: sort counters alphabetically + shared logic between mobile & web

---

src/web/feature-counter/components/SelectCounterPage.tsx

Refs #UPS-4869
---
Ticket: https://jira.uitdatabank.be/browse/...

fix: don't hide search box when no results

---

src/mobile/feature-saving/components/MobileSavingPage.tsx

Problem:
- Search for 0002301383119
- This is an expired kansenstatuut, and shows an error
- Now search for 0900000045410
- Issue: Error from the first card is still shown

fix: don't show alert from previous card

---

src/mobile/feature-saving/components/OpportunityStatePassholder.tsx
src/shared/lib/utils/typescriptUtil.ts

style: simplify component

---

src/mobile/feature-activities/components/ActivitiesPage.tsx
src/mobile/feature-activities/useActivity.ts
src/shared/feature-events/getEventParams.ts
src/web/feature-activities/components/ActivitiesPage.tsx

Ticket: https://jira.uitdatabank.be/browse/UPS-5427

fix: use correct query params to search for event

---

.env.example
package.json
src/app/layout.tsx
src/shared/feature-config/getConfig.ts
src/shared/feature-config/types.ts
src/shared/feature-google-analytics/AnalyticsProvider.tsx
src/shared/feature-google-analytics/context/AnalyticsContext.ts
src/shared/feature-google-analytics/context/useAnalytics.ts
yarn.lock

- Google Analytics provider around entire app, including its context and a `useAnalytics` hook to easily access analytics functions.
---
Ticket: [https://jira.publiq.be/browse/UPS-5400](#UPS-5400)

feat: add Google Analytics integration

---

src/mobile/feature-counter/context/useCounter.ts
src/mobile/layouts/navbar/MobileNavBar.tsx

- Clicking the UiTPAS logo in the top left corner will redirect the user to the counter selection page.
- Added cursor pointer effect on already existing logout button.
---
Ticket: [#UPS-5436](https://jira.publiq.be/browse/UPS-5436)

feat: clicking logo will redirect to counter selection page

---

src/mobile/feature-identification/scan/components/BarcodeScanner.tsx
src/shared/lib/utils/hooks/useCamera.ts

- Saving the previously selected camera in localstorage for the next time the user uses the camera. 
---
Ticket: [#UPS-5437](https://jira.publiq.be/browse/UPS-5437)

feat: remember last used camera for next time use

---

src/shared/feature-events/getEventParams.ts

Ticket: https://jira.uitdatabank.be/browse/UPS-5435

fix: events are refetched on every render
